### PR TITLE
Fix some issues in R CMD CHECK.

### PR DESCRIPTION
**Pull request by arilamstein**
Work on having the package pass R CMD CHECK.
- Fix License issue.
- Add necessary packages to Imports (they were previously simply missing).
- Specify which package/function combination we want R to use via `@importFrom`. Note: the snippets that github shows below are not enough to be sure that I did it right. You will need to look at each function separately to make sure I chose the right one. In this PR I mostly picked the "easy" ones where there was little or no ambiguity. As we progress in this project, though, having a person more knowledgeable with the code make these decisions will be more important. Each of these `@importFrom` NOTES addresses a `no visible global function definition for` NOTE from R CMD CHECK.

### CODE REVIEW

**Comment by dholstius** [comment]
@arilamstein, I'm sorry, but I didn't read through this PR before merging #24 .

Do you know of a way to (easily?) roll back #24 so I can evaluate this PR? Or resolve the conflicts another way?

The commits in this PR look good to my eyeballs.

**Comment by arilamstein** [comment]
Good question.

I am sure that there is some command-line kung fu to do this. But it also appears that on the PR webpage github has two buttons ("restore branch" and "revert" - highlighted below that can do that for you).

Screen Shot 2021-04-12 at 1 15 28 PM

(This screenshot is from #24)

Another alternative (and I don't mind doing this at all), is just for me to merge mainline / master into my PR and resolve all the conflicts there. I could then let you know when the updated PR is ready for your review.

**Comment by dholstius** [comment]
Woohoo, restore-branch then revert worked! Thanks @arilamstein

**Review by dholstius — APPROVED** [review]

**Comment by dholstius** [comment]
Thanks! Leaving your `alamstein-check` branch alone, in case you're planning to use it to do more work.

**Pull request merged**
